# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - gamers-hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Optional: environment variables can be injected here
# You can add these variables in your repository Settings - Secrets and variables - Actions - variables
env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
      packages: write # Required to publish docker image

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username as container tags must be lowercase
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        id: push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' }} # always build the container (incl. Pull Requests), but only push to the registry on code push
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    if: github.event_name == 'push' # Only deploy on push events
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_064CD7E7E5114739ABCE9BB2B163CE1D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B3D733E985004A52A2B3BF4DEC4D24EA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3D276DCA6BBC43ECB825BF1FDD950BBB }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "gamers-hub"
          slot-name: "Production"
          package: .
  deploy-container:
    if: github.event_name == 'push' # Only deploy on push events
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp-container.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Lowercase the repo name and username as container tags must be lowercase
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp-container
        uses: azure/webapps-deploy@v2
        with:
          app-name: "gamers-hub-cnt"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_CONTAINER_PUBLISH_PROFILE }}
          images: "${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}"
